import sys, os, json
sys.stdout.reconfigure(encoding="utf-8")
BASE = os.path.dirname(os.path.abspath(__file__))

parts = []
def L(s=""):
    parts.append(s)

# ── HEADER ──
L('#!/usr/bin/env python3')
L('"""CFI Website Server — Single-file backend, zero third-party deps"""')
L('import http.server, json, sqlite3, os, re, urllib.parse, html as html_mod')
L('import mimetypes, hashlib, uuid, io, datetime, math, shutil')
L('from pathlib import Path')
L('')
L('BASE_DIR = Path(__file__).parent.resolve()')
L('DATA_DIR = BASE_DIR / "data"')
L('STATIC_DIR = BASE_DIR / "static"')
L('UPLOAD_DIR = DATA_DIR / "uploads"')
L('DB_PATH = DATA_DIR / "site.db"')
L('ENV = os.environ.get("CFI_ENV","development")')
L('HOST = os.environ.get("CFI_HOST","127.0.0.1")')
L('PORT = int(os.environ.get("CFI_PORT","7010"))')
L('ADMIN_USER = os.environ.get("CFI_ADMIN_USER","admin")')
L('ADMIN_PASSWORD = os.environ.get("CFI_ADMIN_PASSWORD","cfi2026")')
L('SECRET_KEY = os.environ.get("CFI_SECRET",hashlib.sha256(str(uuid.uuid4()).encode()).hexdigest()[:32])')
L('UPLOAD_IMAGE_MAX = 5242880')
L('UPLOAD_PDF_MAX = 20971520')
L('ALLOWED_IMAGES = {".jpg",".jpeg",".png"}')
L('ALLOWED_DOCS = {".pdf"}')

# ── DB HELPERS ──
L('')
L('def get_db():')
L('    db = sqlite3.connect(str(DB_PATH))')
L('    db.row_factory = sqlite3.Row')
L('    db.execute("PRAGMA journal_mode=WAL")')
L('    db.execute("PRAGMA foreign_keys=ON")')
L('    return db')
L('')
L('def esc(t):')
L('    return "" if t is None else html_mod.escape(str(t))')
L('')
L('def slugify(text):')
L('    t = str(text).strip().lower()')
L('    t = re.sub(r"[^\\w\\s-]","",t)')
L('    t = re.sub(r"[\\s_]+","-",t)')
L('    return re.sub(r"-+","-",t).strip("-")')
L('')
L('def get_setting(db, key, default=""):')
L('    r = db.execute("SELECT value FROM site_settings WHERE key=?",(key,)).fetchone()')
L('    return r["value"] if r else default')
L('')
L('def parse_tags(t):')
L('    return [x.strip() for x in t.split(",") if x.strip()] if t else []')

# ── INIT DB ──
L('')
L('def init_db():')
L('    os.makedirs(DATA_DIR, exist_ok=True)')
L('    os.makedirs(UPLOAD_DIR, exist_ok=True)')
L('    db = get_db()')
L('    db.executescript("""')
L('    CREATE TABLE IF NOT EXISTS site_settings (')
L('        key TEXT PRIMARY KEY,')
L('        value TEXT NOT NULL DEFAULT ""')
L('    );')
L('    CREATE TABLE IF NOT EXISTS navigation (')
L('        id INTEGER PRIMARY KEY AUTOINCREMENT,')
L('        title TEXT NOT NULL,')
L('        title_en TEXT DEFAULT "",')
L('        url TEXT NOT NULL DEFAULT "/",')
L('        sort_order INTEGER NOT NULL DEFAULT 0,')
L('        is_external INTEGER NOT NULL DEFAULT 0')
L('    );')
L('    CREATE TABLE IF NOT EXISTS plans (')
L('        id INTEGER PRIMARY KEY AUTOINCREMENT,')
L('        title TEXT NOT NULL,')
L('        subtitle TEXT DEFAULT "",')
L('        description TEXT NOT NULL DEFAULT "",')
L('        slug TEXT UNIQUE NOT NULL,')
L('        external_url TEXT DEFAULT "",')
L('        sort_order INTEGER NOT NULL DEFAULT 0,')
L('        is_active INTEGER NOT NULL DEFAULT 1,')
L('        created_at TEXT DEFAULT (datetime("now","localtime")),')
L('        updated_at TEXT DEFAULT (datetime("now","localtime"))')
L('    );')
L('    CREATE TABLE IF NOT EXISTS articles (')
L('        id INTEGER PRIMARY KEY AUTOINCREMENT,')
L('        title TEXT NOT NULL,')
L('        slug TEXT UNIQUE NOT NULL,')
L('        summary TEXT DEFAULT "",')
L('        content TEXT NOT NULL DEFAULT "",')
L('        tags TEXT DEFAULT "",')
L('        is_published INTEGER NOT NULL DEFAULT 1,')
L('        created_at TEXT DEFAULT (datetime("now","localtime")),')
L('        updated_at TEXT DEFAULT (datetime("now","localtime"))')
L('    );')
L('    CREATE TABLE IF NOT EXISTS reports (')
L('        id INTEGER PRIMARY KEY AUTOINCREMENT,')
L('        title TEXT NOT NULL,')
L('        slug TEXT UNIQUE NOT NULL,')
L('        summary TEXT DEFAULT "",')
L('        content TEXT NOT NULL DEFAULT "",')
L('        tags TEXT DEFAULT "",')
L('        report_type TEXT DEFAULT "research",')
L('        pdf_filename TEXT DEFAULT "",')
L('        is_published INTEGER NOT NULL DEFAULT 1,')
L('        created_at TEXT DEFAULT (datetime("now","localtime")),')
L('        updated_at TEXT DEFAULT (datetime("now","localtime"))')
L('    );')
L('    CREATE TABLE IF NOT EXISTS researchers (')
L('        id INTEGER PRIMARY KEY AUTOINCREMENT,')
L('        name TEXT NOT NULL,')
L('        slug TEXT UNIQUE NOT NULL,')
L('        title TEXT DEFAULT "",')
L('        bio TEXT DEFAULT "",')
L('        photo TEXT DEFAULT "",')
L('        tags TEXT DEFAULT "",')
L('        is_active INTEGER NOT NULL DEFAULT 1,')
L('        created_at TEXT DEFAULT (datetime("now","localtime"))')
L('    );')
L('    CREATE TABLE IF NOT EXISTS courses (')
L('        id INTEGER PRIMARY KEY AUTOINCREMENT,')
L('        title TEXT NOT NULL,')
L('        slug TEXT UNIQUE NOT NULL,')
L('        description TEXT DEFAULT "",')
L('        instructor TEXT DEFAULT "",')
L('        qr_code TEXT DEFAULT "",')
L('        external_url TEXT DEFAULT "",')
L('        is_active INTEGER NOT NULL DEFAULT 1,')
L('        created_at TEXT DEFAULT (datetime("now","localtime"))')
L('    );')
L('    """)')
L('    if not db.execute("SELECT COUNT(*) FROM navigation").fetchone()[0]:')
L('        for i,(t,u) in enumerate([("首页","/"),("关于","/about"),("计划","/plans"),("产出","/output"),("社群","/community"),("合作","/contact")]):')
L('            db.execute("INSERT INTO navigation(title,url,sort_order) VALUES(?,?,?)",(t,u,i))')
L('    defaults = {"hero_title":"用社群力量<br>重塑未来","hero_subtitle":"由残障人发起并领导的独立民间研究机构","statement_01_title":"关于我们","statement_01_body":"酷残未来研究院（CFI）是中国首个由残障人发起并领导的独立民间残障研究机构。","statement_02_title":"背景与失语","statement_02_body":"残障研究领域长期缺乏残障人的主体视角。CFI旨在打破这种失语状态。","statement_03_title":"核心方法论","statement_03_body":"我们采用社群参与式研究方法，确保每一项研究都扎根于真实社群需求。","vision_title":"战略愿景","vision_body":"在未来五年内，建设成为中国最具影响力的残障研究社群组织。","support_body":"您的支持将帮助我们持续开展残障研究、社群建设和政策倡导工作。","footer_email":"contact@crippingfuture.org"}')
L('    for k,v in defaults.items():')
L('        db.execute("INSERT OR IGNORE INTO site_settings(key,value) VALUES(?,?)",(k,v))')
L('    db.commit(); db.close()')
